### ISSUE TITLE
As a User, I want to be able to understand the value proposition of spotify_calendar

### ISSUE THREAD

**Issue by Ciboulette** [Ciboulette/spotify_calendar#5]
### TODOS

- [ ] Create a simple landing page
- [ ] Create a twitter account
- [ ] Product Hunt (once the key feature is 👌)
